# Generated by Django 2.1.5 on 2019-01-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('update_at', models.TimeField(auto_now=True)),
            ],
        ),
    ]
